POSITIVE_SAYINGS = [
    "Every path leads to gold.",
    "It's all wins, no losses.",
    "The sun shines brighter every day.",
    "You either thrive or you thrive harder.",
    "The glass isn't just half full—it's overflowing.",
    "Every turn is the right one.",
    "It's all good vibes, all the time.",
    "Every seed grows into a tree.",
    "The jackpot is always yours.",
    "Life's a buffet of blessings.",
    "Success knocks twice.",
    "Every shot hits the mark.",
    "Fortune follows your lead.",
    "Rainbows are everywhere you look.",
    "The stars align every night.",
    "You're always one step ahead.",
    "Every move's a power move.",
    "The world is your oyster, every time.",
    "Sunsets and rises, all in your favor.",
    "Every roll is a lucky roll.",
    "You either shine or shine brighter.",
    "All roads lead to victory.",
    "Every wave lifts your ship.",
    "Your harvest is always abundant.",
    "You're the main character in every story.",
    "Every climb reaches the peak.",
    "You're on a perpetual winning streak.",
    "Every chapter's a bestseller.",
    "The wind always fills your sails.",
    "You're batting a thousand, every time.",
    "Every day's a golden ticket.",
    "You're always in the winner's circle.",
    "Every song is a hit single.",
    "Luck is your middle name.",
    "Every lane is your fast lane.",
    "You don't just win—you overachieve.",
    "Every step is on solid gold.",
    "You don't just dream—you achieve.",
    "Every toss lands heads up.",
    "The universe conspires in your favor.",
    "Every day's a walk in the park.",
    "You're always on the right track.",
    "Every sunrise is your spotlight.",
    "The dice always roll your way.",
    "Your fortune cookie is always right.",
    "Every wish comes true instantly.",
    "You're swimming in a sea of success.",
    "Every season is your winning season.",
    "You're always catching the big fish.",
    "The pot of gold is always at your feet.",
]

RESPECT_SAYINGS = [
    "You either love it or love it.",
    "You either accept it or accept it.",
    "You either embrace it or embrace it.",
    "You either honor it or honor it.",
    "You either value it or value it.",
    "You either appreciate it or appreciate it.",
    "You either trust it or trust it.",
    "You either believe it or believe it.",
    "You either learn it or learn it.",
    "You either support it or support it.",
    "You either agree with it or agree with it.",
    "You either grow with it or grow with it.",
    "You either see it or see it.",
    "You either own it or own it.",
    "You either vibe with it or vibe with it.",
    "You either follow it or follow it.",
    "You either lead it or lead it.",
    "You either show up or show up.",
    "You either feel it or feel it.",
    "You either win it or win it.",
    "You either get it or get it.",
    "You either want it or want it.",
    "You either claim it or claim it.",
    "You either commit or commit.",
    "You either elevate or elevate.",
    "You either choose it or choose it.",
    "You either face it or face it.",
    "You either rise to it or rise to it.",
    "You either earn it or earn it.",
    "You either master it or master it.",
    "You either do it or do it.",
    "You either push it or push it.",
    "You either hustle or hustle.",
    "You either make it or make it.",
    "You either respect the process or respect the process.",
    "You either build it or build it.",
    "You either live it or live it.",
    "You either trust the grind or trust the grind.",
    "You either create it or create it.",
    "You either go hard or go hard.",
    "You either show love or show love.",
    "You either give it your all or give it your all.",
    "You either level up or level up.",
    "You either stay focused or stay focused.",
    "You either keep going or keep going.",
    "You either own the moment or own the moment.",
    "You either step up or step up.",
    "You either shine or shine.",
    "You either respect greatness or respect greatness.",
    "You either stay winning or stay winning.",
]
